# Generated by Django 5.2.6 on 2025-10-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoo',
            name='email',
        ),
    ]
