# Generated by Django 5.2.6 on 2025-10-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0005_rename_idno_todoo_srno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='todoo',
            name='srno',
        ),
        migrations.AddField(
            model_name='todoo',
            name='idno',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
