# Generated by Django 5.2.6 on 2025-10-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0006_task_remove_todoo_srno_todoo_idno'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign_up_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='todoo',
            old_name='idno',
            new_name='srno',
        ),
    ]
