# Generated by Django 5.2.6 on 2025-10-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0008_alter_sign_up_list_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up_list',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
