# Generated by Django 5.2.6 on 2025-10-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0019_signuplist_alter_sign_up_list_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign_up_list',
        ),
    ]
