# Generated by Django 5.2.6 on 2025-10-15 17:44

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0002_remove_todoo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='email',
            field=models.EmailField(default=1, max_length=25, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
