# Generated by Django 5.2.6 on 2025-10-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0003_todoo_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoo',
            old_name='srno',
            new_name='idno',
        ),
    ]
