# Generated by Django 5.2.6 on 2025-10-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0004_rename_srno_todoo_idno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoo',
            old_name='idno',
            new_name='srno',
        ),
    ]
