# Generated by Django 5.2.6 on 2025-10-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0007_sign_up_list_rename_idno_todoo_srno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up_list',
            name='password',
            field=models.IntegerField(max_length=50),
        ),
    ]
