# Generated by Django 5.2.6 on 2025-10-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0009_alter_sign_up_list_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up_list',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
