# Generated by Django 5.2.6 on 2025-10-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0013_alter_sign_up_list_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up_list',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
