# Generated by Django 5.2.6 on 2025-10-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0014_alter_sign_up_list_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up_list',
            name='email',
            field=models.EmailField(blank=True, default='default@example.com', max_length=100),
            preserve_default=False,
        ),
    ]
