# Generated by Django 5.2.6 on 2025-10-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0018_alter_sign_up_list_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='sign_up_list',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
