# Generated by Django 5.2.6 on 2025-10-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0020_delete_sign_up_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUpList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
