# Generated by Django 5.2.6 on 2025-10-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentmood', '0021_loginuplist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Todoo',
        ),
    ]
